//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.bit.ueh.edu.vn/", ConfigurationName="ServiceReference.CalculatorWs")]
    public interface CalculatorWs
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/addRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/addResponse")]
        System.Threading.Tasks.Task<ServiceReference.addResponse> addAsync(ServiceReference.addRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/multiplyResponse")]
        System.Threading.Tasks.Task<ServiceReference.multiplyResponse> multiplyAsync(ServiceReference.multiplyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/subtractRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/subtractResponse")]
        System.Threading.Tasks.Task<ServiceReference.subtractResponse> subtractAsync(ServiceReference.subtractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.bit.ueh.edu.vn/CalculatorWs/divideRequest", ReplyAction="http://services.bit.ueh.edu.vn/CalculatorWs/divideResponse")]
        System.Threading.Tasks.Task<ServiceReference.divideResponse> divideAsync(ServiceReference.divideRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="add", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public addRequest()
        {
        }
        
        public addRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class addResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public addResponse()
        {
        }
        
        public addResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiply", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public multiplyRequest()
        {
        }
        
        public multiplyRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="multiplyResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class multiplyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public multiplyResponse()
        {
        }
        
        public multiplyResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtract", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public subtractRequest()
        {
        }
        
        public subtractRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="subtractResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class subtractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int @return;
        
        public subtractResponse()
        {
        }
        
        public subtractResponse(int @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divide", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int arg1;
        
        public divideRequest()
        {
        }
        
        public divideRequest(int arg0, int arg1)
        {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="divideResponse", WrapperNamespace="http://services.bit.ueh.edu.vn/", IsWrapped=true)]
    public partial class divideResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public divideResponse()
        {
        }
        
        public divideResponse(double @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface CalculatorWsChannel : ServiceReference.CalculatorWs, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class CalculatorWsClient : System.ServiceModel.ClientBase<ServiceReference.CalculatorWs>, ServiceReference.CalculatorWs
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalculatorWsClient() : 
                base(CalculatorWsClient.GetDefaultBinding(), CalculatorWsClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CalculatorWsImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorWsClient(EndpointConfiguration endpointConfiguration) : 
                base(CalculatorWsClient.GetBindingForEndpoint(endpointConfiguration), CalculatorWsClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorWsClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalculatorWsClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorWsClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalculatorWsClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculatorWsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.addResponse> ServiceReference.CalculatorWs.addAsync(ServiceReference.addRequest request)
        {
            return base.Channel.addAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.addResponse> addAsync(int arg0, int arg1)
        {
            ServiceReference.addRequest inValue = new ServiceReference.addRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ServiceReference.CalculatorWs)(this)).addAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.multiplyResponse> ServiceReference.CalculatorWs.multiplyAsync(ServiceReference.multiplyRequest request)
        {
            return base.Channel.multiplyAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.multiplyResponse> multiplyAsync(int arg0, int arg1)
        {
            ServiceReference.multiplyRequest inValue = new ServiceReference.multiplyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ServiceReference.CalculatorWs)(this)).multiplyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.subtractResponse> ServiceReference.CalculatorWs.subtractAsync(ServiceReference.subtractRequest request)
        {
            return base.Channel.subtractAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.subtractResponse> subtractAsync(int arg0, int arg1)
        {
            ServiceReference.subtractRequest inValue = new ServiceReference.subtractRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ServiceReference.CalculatorWs)(this)).subtractAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference.divideResponse> ServiceReference.CalculatorWs.divideAsync(ServiceReference.divideRequest request)
        {
            return base.Channel.divideAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference.divideResponse> divideAsync(int arg0, int arg1)
        {
            ServiceReference.divideRequest inValue = new ServiceReference.divideRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((ServiceReference.CalculatorWs)(this)).divideAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculatorWsImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CalculatorWsImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8080/Gradle___vn_edu_ueh_bit___demo_1_0_SNAPSHOT_war/calculatorW" +
                        "ebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalculatorWsClient.GetBindingForEndpoint(EndpointConfiguration.CalculatorWsImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalculatorWsClient.GetEndpointAddress(EndpointConfiguration.CalculatorWsImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CalculatorWsImplPort,
        }
    }
}
